### ISSUE TITLE
Handle Git Tag Deletions

### ISSUE THREAD

**Issue by tmapes** [go-vela/server#103]
## Description
If a remote tag is deleted, do not trigger a build.

## Value

This prevents un-necessary builds attempting to queue in Vela and also would mark the Hook as passed in GitHub (currently a tag deletion marks the hook push as failed due to Vela failing to find a commit to build off of)

## Definition of Done

Deleting a remote git tag does not attempt to trigger a build.

## Effort  (Optional)

Unsure, however it looks like the GitHub published message has a root level `deleted` boolean which is set to `true` on deletes.  
This paired with the root level `ref` key being set to `refs/tags/*` should allow Vela to gracefully handle this.

**Comment by tmapes** [comment]
This might be done already. The newest release doesn't seem to be triggering builds for me on tag deletions.

**Comment by kneal** [comment]
@tmapes are you okay with is closing this one for now then?

**Comment by tmapes** [comment]
Closing!

**Comment by kneal** [comment]
Thanks!
