### ISSUE TITLE
Limit concurrency of builds

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/server#123]
## Description

Enable the ability to limit the concurrent running vela pipelines for a given repository and/or given branches within the repository.

Some extra thoughts needed for considerations:

- should the setting be defined within the `.vela.yml` and/or settings page of the UI?
- should builds be queued if the limit is reached or have the webhook return some error?

## Value

This is primarily helpful for repositories that are implementing deployments, and having multiple run at the same time can cause unintended behavior.

## Definition of Done

Users are able to define the concurrency of running vela pipelines within the API.

## Impacted Personas (Optional)

- All users

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ go-vela/community.

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
