### ISSUE TITLE
Expose PR branch as environment variable

### ISSUE THREAD

**Issue by jmcnevin** [go-vela/server#127]
## Description

In a pull request event, `BUILD_BRANCH` is populated with the name of the base branch that the PR is targeting, but it would be nice to have access to the pull request branch name as well.

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ go-vela/community.

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
