### ISSUE TITLE
JWT expiration & refresh token

### ISSUE THREAD

**Issue by wass3r** [go-vela/server#134]
## Description

_Note: This change will be taking place in multiple places/repos - other stories to follow._

Currently, JWT returned by the server lives indefinitely. The client is responsible for retiring it. This change will introduce expiration for the JWT to make it short-lived and introduce a long-lived refresh token.

## Value

Improved security.

## Definition of Done

Server returns JWT + Refresh Token with expiration. Provides means to retrieve new JWT via refresh token endpoint. Expired JWT, Refresh Token prevents access.

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
