### ISSUE TITLE
Allow vela projects and builds to be viewed by authenticated users

### ISSUE THREAD

**Issue by kneal** [go-vela/server#87]
## Description

_What is your idea?_

## Value

_Why is this important? Who does it impact? Will this make something better, faster, etc?_

## Definition of Done

_What is the end goal of this story?_

## Effort  (Optional)

_Estimated effort to complete this story? (Best Guess e.g. 1-2 days)_

## Impacted Personas (Optional)

_Which personas will benefit from completing this story? (Users, Administrators, etc)_

**Comment by jbrockopp** [comment]
This story is complete 👍 🎉
