### ISSUE TITLE
Enable removal of deleted repositories

### ISSUE THREAD

**Issue by rmurray-tgt** [go-vela/server#95]
## Description

If a repo is deleted from git, it will still appear in Vela and cannot be removed. Please allow repositories that have been deleted from git to be removed from vela.

## Value

The current workaround is to recreate the repo, remove from vela, and re-delete. These added steps cost time.

## Definition of Done

If a git repo no longer exists, a user will still be able to remove them

**Comment by jbrockopp** [comment]
Hello 👋

The Vela admins have decided to condense all existing issues into a single repo found @ go-vela/community.

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
